trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - liquibase

jobs:
- job: Build
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:
  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      repository: jakepelter/pets-liquibase
      dockerfile: liquibase/Dockerfile
      tags: |
        $(Build.BuildId)
  - task: Docker@2
    displayName: Push
    inputs:
      command: push
      repository: jakepelter/pets-liquibase
      containerRegistry: 'jakep-dockerhub'
      tags: |
        $(Build.BuildId)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: liquibase/charts
      artifactName: 'drop'