# NEED TO ADD IMAGETAG AND HOSTNAME AS VALUES IN HELM DEPLOYMENT!
image: docker.io/jakepelter/patel-pets-api
imageTag:
imagePullSecret: jakep-dockerhub

port: 8080
rpm: 100
hostname:

postgresURL:
postgresSecret: