trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - react-frontend

schedules:
- cron: 0 0 * * * # MIDNIGHT UTC BUILD!
  branches:
    include:
    - main
  always: true

jobs:
- job: Build
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:
  - task: Docker@2
    displayName: Build
    inputs:
      command: buildAndPush
      repository: jakepelter/patel-pets-website
      dockerfile: react-frontend/Dockerfile
      containerRegistry: containerRegistry: 'jakep-dockerhub'
      tags: $(Build.BuildId)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: react-frontend/charts
      artifactName: 'drop'